title: Guia GAC Brasil
description: Repositório colaborativo com informações a respeito dos veículos da GAC no Brasil.
url: "https://guia-gac-brasil.github.io"
baseurl: "" 

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "dark" 
minimal_mistakes_skin2: "default"

footer_scripts:
  - /assets/js/custom-theme-toggle.js

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      sidebar:
        nav: "side_menu"
